const enumLabels: Record<string, string> = {
  Draft: 'Rascunho',
  New: 'Novo',
  Submitted: 'Enviado',
  Accepted: 'Aceito',
  Confirmed: 'Confirmado',
  Seated: 'Recepcionado',
  NoShow: 'Não compareceu',
  Waiting: 'Aguardando',
  Notified: 'Avisado',
  InProduction: 'Em preparo',
  Preparing: 'Em preparo',
  Ready: 'Pronto',
  Completed: 'Concluído',
  Complete: 'Conclusão',
  Cancelled: 'Cancelado',
  Pending: 'Pendente',
  Acknowledged: 'Assumido',
  InProgress: 'Em atendimento',
  Authorized: 'Autorizado',
  Paid: 'Pago',
  Failed: 'Falhou',
  Refunded: 'Estornado',
  PartiallyRefunded: 'Parcialmente estornado',
  Open: 'Aberto',
  Closing: 'Em fechamento',
  Closed: 'Fechado',
  Online: 'Conectado',
  Offline: 'Desconectado',
  Idle: 'Ocioso',
  Blocked: 'Bloqueado',
  Maintenance: 'Em manutenção',
  DineIn: 'Salão',
  Delivery: 'Entrega',
  AwaitingPreparation: 'Aguardando preparo',
  ReadyForDispatch: 'Pronto para despacho',
  Dispatched: 'Saiu para entrega',
  Delivered: 'Entregue',
  Pickup: 'Retirada',
  Takeaway: 'Retirada',
  Website: 'Site',
  Application: 'Aplicativo',
  Administrative: 'Administrativo',
  Standard: 'Padrão',
  Pizza: 'Pizza',
  PizzaFlavor: 'Sabor de pizza',
  Beverage: 'Bebida',
  Portion: 'Porção',
  Dessert: 'Sobremesa',
  Additional: 'Adicional',
  Savory: 'Salgado',
  Sweet: 'Doce',
  Administrator: 'Administrador',
  Create: 'Criação',
  confirm: 'Confirmação',
  start: 'Início do preparo',
  ready: 'Pronto',
  SplitPayment: 'Pagamento dividido',
  Update: 'Atualização',
  Pay: 'Pagamento',
  Request: 'Solicitação',
  OpenTable: 'Abertura de mesa',
  CashIn: 'Suprimento',
  CashOut: 'Sangria',
  Supply: 'Suprimento',
  Withdrawal: 'Sangria',
  Sale: 'Venda',
  Catalog: 'Cardápio',
  Dining: 'Salão',
  Production: 'Produção',
  Billing: 'Financeiro',
  KitchenTicket: 'Ticket da cozinha',
  Bill: 'Conta',
  Product: 'Produto',
  TableSession: 'Atendimento de mesa',
  CustomerTablet: 'Tablet do cliente',
  Printer: 'Impressora',
  Network: 'Rede',
  HighestFlavorPrice: 'Maior valor entre os sabores',
  AverageFlavorPrice: 'Média dos sabores',
  ProportionalFlavorPrice: 'Valor proporcional',
}

export function translateEnum(value?: string | null) {
  if (!value) return 'Não informado'
  return enumLabels[value] ?? value
}

export function enumCssToken(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/\s+/g, '-')
    .toLowerCase()
}
