export const queryKeys = {
  all: ['admin'] as const,
  dashboard: ['admin', 'dashboard'] as const,
  tables: ['admin', 'tables'] as const,
  table: (id: string) => ['admin', 'tables', id] as const,
  categories: ['admin', 'categories'] as const,
  products: ['admin', 'products'] as const,
  pizzaSizes: ['admin', 'pizza-sizes'] as const,
  pizzaFlavors: ['admin', 'pizza-flavors'] as const,
  pizzaRules: ['admin', 'settings', 'pizza-rules'] as const,
  kitchenTickets: ['admin', 'kitchen', 'tickets'] as const,
  orders: ['admin', 'orders'] as const,
  crusts: ['admin', 'pizza-crusts'] as const,
  unitSettings: ['admin', 'settings', 'unit'] as const,
  operationSettings: ['admin', 'settings', 'operation'] as const,
  cashRegisters: ['admin', 'cashier', 'registers'] as const,
  cashShift: ['admin', 'cashier', 'current'] as const,
  paymentMethods: ['admin', 'payment-methods'] as const,
  payments: ['admin', 'payments'] as const,
  financialReport: (from?: string, to?: string) => ['admin', 'reports', 'financial', from, to] as const,
  devices: ['admin', 'devices'] as const,
  users: ['admin', 'users'] as const,
  roles: ['admin', 'roles'] as const,
  audit: ['admin', 'audit'] as const,
  systemSnapshot: ['admin', 'system', 'snapshot'] as const,
}
