namespace ProjetoPizza.Application.Admin;

public interface IAdminManagementService
{
    Task<IReadOnlyCollection<OrderManagementDto>> ListOrdersAsync(CancellationToken cancellationToken);
    Task<OrderReceiptDto?> GetOrderReceiptAsync(Guid id, CancellationToken cancellationToken);
    Task<AdministrativeOrderCatalogDto> GetOrderCatalogAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<CustomerDto>> ListCustomersAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<ReservationDto>> ListReservationsAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<WaitlistEntryDto>> ListWaitlistAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<PizzaCrustDto>> ListPizzaCrustsAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<IngredientDto>> ListIngredientsAsync(CancellationToken cancellationToken);
    Task<UnitSettingsDto> GetUnitSettingsAsync(CancellationToken cancellationToken);
    Task<OperationSettingsDto> GetOperationSettingsAsync(CancellationToken cancellationToken);
    Task<PizzaRulesDto> GetPizzaRulesAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<CashRegisterDto>> ListCashRegistersAsync(CancellationToken cancellationToken);
    Task<CashShiftDto?> GetCurrentCashShiftAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<CashShiftHistoryDto>> ListCashShiftHistoryAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<PaymentMethodDto>> ListPaymentMethodsAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<PaymentDto>> ListPaymentsAsync(CancellationToken cancellationToken);
    Task<FinancialReportDto> GetFinancialReportAsync(DateTimeOffset from, DateTimeOffset to, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DeviceDto>> ListDevicesAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<PrintJobDto>> ListPrintJobsAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<AuditLogDto>> ListAuditLogsAsync(CancellationToken cancellationToken);
    Task<SystemSnapshotDto> CreateSystemSnapshotAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DiningAreaAdminDto>> ListDiningAreasAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<RestaurantTableAdminDto>> ListRestaurantTableSettingsAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<ProductionStationAdminDto>> ListProductionStationsAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<ServiceCallTypeAdminDto>> ListServiceCallTypesAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<InventoryItemAdminDto>> ListInventoryItemsAsync(CancellationToken cancellationToken);
    Task<IReadOnlyCollection<RecipeAdminDto>> ListRecipesAsync(CancellationToken cancellationToken);

    Task UpdateUnitAsync(UpdateUnitCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task UpdateOperationSettingsAsync(UpdateOperationSettingsCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task UpdatePizzaRulesAsync(UpdatePizzaRulesCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveCategoryAsync(SaveCategoryCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveProductAsync(SaveProductCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveProductImageAsync(Guid productId, Stream content, string contentType, string fileName, string altText, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SavePizzaSizeAsync(SavePizzaSizeCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SavePizzaCrustAsync(SavePizzaCrustCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveIngredientAsync(SaveIngredientCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SavePizzaFlavorAsync(SavePizzaFlavorCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SavePizzaFlavorImageAsync(Guid flavorId, Stream content, string contentType, string fileName, Guid identityUserId, CancellationToken cancellationToken);
    Task<CustomerDto> SaveCustomerAsync(SaveCustomerCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<ReservationDto> CreateReservationAsync(CreateReservationCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> TransitionReservationAsync(Guid id, string transition, Guid identityUserId, CancellationToken cancellationToken);
    Task<WaitlistEntryDto> CreateWaitlistEntryAsync(CreateWaitlistEntryCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> TransitionWaitlistEntryAsync(Guid id, string transition, Guid identityUserId, CancellationToken cancellationToken);
    Task<CreatedOrderDto> CreateOrderAsync(CreateAdministrativeOrderCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CounterCheckoutResultDto> CheckoutCounterOrderAsync(CheckoutCounterOrderCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> OpenTableAsync(OpenTableCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> AssignTableWaiterAsync(Guid tableSessionId, AssignTableWaiterCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> LinkTableAsync(Guid tableSessionId, LinkTableCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> TransferTableAsync(Guid tableSessionId, TransferTableCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> RequestBillAsync(Guid tableSessionId, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> TransitionOrderAsync(Guid id, string transition, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> CancelOrderAsync(Guid id, CancelOrderCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> ApplyOrderDiscountAsync(Guid id, ApplyOrderDiscountCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> DispatchDeliveryAsync(Guid id, string driverName, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> CompleteDeliveryAsync(Guid id, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> FailDeliveryAsync(Guid id, string reason, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> TransitionKitchenTicketAsync(Guid id, string transition, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> AcknowledgeServiceCallAsync(Guid id, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> CompleteServiceCallAsync(Guid id, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> RecordPaymentAsync(RecordPaymentCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> RecordSplitPaymentAsync(RecordSplitPaymentCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> RefundPaymentAsync(Guid id, RefundPaymentCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CashShiftDto> OpenCashShiftAsync(OpenCashShiftCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> RegisterCashMovementAsync(RegisterCashMovementCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> CloseCashShiftAsync(CloseCashShiftCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> UpdateDeviceAsync(Guid id, UpdateDeviceCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveNetworkPrinterAsync(SaveNetworkPrinterCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> QueuePrinterTestAsync(Guid printerId, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> QueueOrderReceiptAsync(Guid orderId, Guid identityUserId, CancellationToken cancellationToken);
    Task<PrintBatchResultDto> QueueKitchenCommandAsync(Guid orderId, Guid identityUserId, CancellationToken cancellationToken);
    Task<DeviceProvisioningDto> CreateCustomerTabletAsync(CreateCustomerTabletCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<DeviceProvisioningDto> ProvisionCustomerTabletAsync(Guid id, ProvisionCustomerTabletCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveDiningAreaAsync(SaveDiningAreaCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveRestaurantTableAsync(SaveRestaurantTableCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveCashRegisterAsync(SaveCashRegisterCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SavePaymentMethodAsync(SavePaymentMethodCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveProductionStationAsync(SaveProductionStationCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveServiceCallTypeAsync(SaveServiceCallTypeCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveInventoryItemAsync(SaveInventoryItemCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> AdjustInventoryAsync(Guid id, AdjustInventoryCommand command, Guid identityUserId, CancellationToken cancellationToken);
    Task<CommandResultDto> SaveRecipeAsync(SaveRecipeCommand command, Guid identityUserId, CancellationToken cancellationToken);
}
